baseURL = "https://jasperdeen.com/"
languageCode = "en-us"
title = "Jasper H. Deen"

enableGitInfo = true
paginate = 10
disablePathToLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  dateFormat = "January 2, 2006"

[params.author]
  name = "Jasper H. Deen"
  email = "jasperhdeen@gmail.com"

[[params.nav]]
  name = "About"
  url = "/"
[[params.nav]]
  name = "Portfolio"
  url = "/writing/"
[[params.nav]]
  name = "Now"
  url = "/now/"
[[params.nav]]
  name = "Timeline"
  url = "/timeline/"
[[params.nav]]
  name = "Resume"
  url = "/resume/"
[[params.nav]]
  name = "Contact"
  url = "/contact/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
